// prisma/seed.ts
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const themes = [
  {
    name: 'Midnight',
    slug: 'midnight',
    description: 'Dark, sleek and professional',
    category: 'DARK',
    isPremium: false,
    sortOrder: 1,
    config: {
      background: '#0f0f0f',
      surface: '#1a1a1a',
      text: '#ffffff',
      textMuted: '#888888',
      accent: '#6366f1',
      buttonBg: '#6366f1',
      buttonText: '#ffffff',
      buttonRadius: '12px',
      fontFamily: "'DM Sans', sans-serif",
      backgroundType: 'solid',
    },
  },
  {
    name: 'Sunrise',
    slug: 'sunrise',
    description: 'Warm gradient vibes',
    category: 'GRADIENT',
    isPremium: false,
    sortOrder: 2,
    config: {
      background: 'linear-gradient(135deg, #f97316 0%, #ec4899 100%)',
      surface: 'rgba(255,255,255,0.15)',
      text: '#ffffff',
      textMuted: 'rgba(255,255,255,0.8)',
      accent: '#fbbf24',
      buttonBg: 'rgba(255,255,255,0.25)',
      buttonText: '#ffffff',
      buttonRadius: '50px',
      fontFamily: "'Poppins', sans-serif",
      backgroundType: 'gradient',
    },
  },
  {
    name: 'Ocean',
    slug: 'ocean',
    description: 'Cool blue tones',
    category: 'GRADIENT',
    isPremium: false,
    sortOrder: 3,
    config: {
      background: 'linear-gradient(180deg, #0ea5e9 0%, #1e3a5f 100%)',
      surface: 'rgba(255,255,255,0.1)',
      text: '#ffffff',
      textMuted: 'rgba(255,255,255,0.75)',
      accent: '#38bdf8',
      buttonBg: 'rgba(255,255,255,0.2)',
      buttonText: '#ffffff',
      buttonRadius: '12px',
      fontFamily: "'Inter', sans-serif",
      backgroundType: 'gradient',
    },
  },
  {
    name: 'Petal',
    slug: 'petal',
    description: 'Soft pastel aesthetics',
    category: 'MINIMAL',
    isPremium: false,
    sortOrder: 4,
    config: {
      background: '#fdf2f8',
      surface: '#ffffff',
      text: '#1f1f2e',
      textMuted: '#9ca3af',
      accent: '#ec4899',
      buttonBg: '#ec4899',
      buttonText: '#ffffff',
      buttonRadius: '50px',
      fontFamily: "'Nunito', sans-serif",
      backgroundType: 'solid',
    },
  },
  {
    name: 'Forest',
    slug: 'forest',
    description: 'Natural earthy greens',
    category: 'COLORFUL',
    isPremium: false,
    sortOrder: 5,
    config: {
      background: '#052e16',
      surface: '#14532d',
      text: '#dcfce7',
      textMuted: '#86efac',
      accent: '#4ade80',
      buttonBg: '#16a34a',
      buttonText: '#ffffff',
      buttonRadius: '8px',
      fontFamily: "'Sora', sans-serif",
      backgroundType: 'solid',
    },
  },
  {
    name: 'Diwali',
    slug: 'diwali',
    description: 'Festive Indian vibes with gold',
    category: 'FESTIVE',
    isPremium: false,
    sortOrder: 6,
    config: {
      background: '#1a0a00',
      surface: '#2d1500',
      text: '#fbbf24',
      textMuted: '#f59e0b',
      accent: '#f97316',
      buttonBg: 'linear-gradient(90deg, #f59e0b, #ef4444)',
      buttonText: '#ffffff',
      buttonRadius: '4px',
      fontFamily: "'Baloo 2', cursive",
      backgroundType: 'solid',
    },
  },
  {
    name: 'Snow',
    slug: 'snow',
    description: 'Clean white minimal',
    category: 'MINIMAL',
    isPremium: false,
    sortOrder: 7,
    config: {
      background: '#ffffff',
      surface: '#f8fafc',
      text: '#0f172a',
      textMuted: '#64748b',
      accent: '#3b82f6',
      buttonBg: '#0f172a',
      buttonText: '#ffffff',
      buttonRadius: '8px',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      backgroundType: 'solid',
    },
  },
  {
    name: 'Neon',
    slug: 'neon',
    description: 'Cyberpunk neon aesthetics',
    category: 'BOLD',
    isPremium: true,
    sortOrder: 8,
    config: {
      background: '#000000',
      surface: '#0d0d0d',
      text: '#00ff88',
      textMuted: '#00cc66',
      accent: '#ff006e',
      buttonBg: 'transparent',
      buttonText: '#00ff88',
      buttonRadius: '0px',
      buttonBorder: '1px solid #00ff88',
      fontFamily: "'Space Mono', monospace",
      backgroundType: 'solid',
    },
  },
  {
    name: 'Royal',
    slug: 'royal',
    description: 'Luxury purple gradient',
    category: 'PROFESSIONAL',
    isPremium: true,
    sortOrder: 9,
    config: {
      background: 'linear-gradient(160deg, #1e1b4b 0%, #312e81 50%, #4c1d95 100%)',
      surface: 'rgba(255,255,255,0.08)',
      text: '#e0e7ff',
      textMuted: '#a5b4fc',
      accent: '#c4b5fd',
      buttonBg: 'linear-gradient(90deg, #7c3aed, #4f46e5)',
      buttonText: '#ffffff',
      buttonRadius: '12px',
      fontFamily: "'Outfit', sans-serif",
      backgroundType: 'gradient',
    },
  },
  {
    name: 'Holi',
    slug: 'holi',
    description: 'Vibrant festive colors',
    category: 'FESTIVE',
    isPremium: false,
    sortOrder: 10,
    config: {
      background: 'linear-gradient(135deg, #f43f5e 0%, #a855f7 33%, #3b82f6 66%, #10b981 100%)',
      surface: 'rgba(255,255,255,0.2)',
      text: '#ffffff',
      textMuted: 'rgba(255,255,255,0.85)',
      accent: '#fbbf24',
      buttonBg: 'rgba(255,255,255,0.3)',
      buttonText: '#ffffff',
      buttonRadius: '50px',
      fontFamily: "'Nunito', sans-serif",
      backgroundType: 'gradient',
    },
  },
];

async function main() {
  console.log('Seeding themes...');
  for (const theme of themes) {
    await prisma.theme.upsert({
      where: { slug: theme.slug },
      update: theme,
      create: theme,
    });
  }
  console.log(`✅ Seeded ${themes.length} themes`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
